---
kind: pipeline
name: default
type: docker

steps:

  - name: lint
    image: golangci/golangci-lint:v1.23.8
    commands:
      - make lint

  - name: test
    image: golang:1.15
    commands:
      - make ci-test

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - coverage.txt

  - name: build
    image: docker
    commands:
      - docker build -t openflag:latest .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
