linters:
  enable-all: true

issues:
  exclude-rules:
    - path: \.go
      linters:
        - stylecheck
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gomnd
        - maligned
    - path: internal/app/openflag/constraint
      linters:
        - dupl
    - path: internal/app/openflag/constraint/parser.go
      linters:
        - gomnd
        - gocognit
        - gocritic

  exclude-use-default: false
