linters:
  enable-all: true

issues:
  exclude-rules:
    - path: \.go
      linters:
        - stylecheck
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gomnd
        - maligned
    - path: internal/app/openflag/constraint
      linters:
        - dupl

  exclude-use-default: false
