logger:
  access:
    enabled: false
    path: "/var/log/openflag/access.log"
    format: "${remote_ip} - - [${time_rfc3339}] \"${method} ${uri} HTTP/1.1\" ${status} \
    ${bytes_out} ${bytes_in} ${latency} \"${referer}\" \"${user_agent}\"\n"
    max-size: 1024
    max-backups: 7
    max-age: 7
  app:
    level: info
    path: "/var/log/openflag/app.log"
    max-size: 1024
    max-backups: 7
    max-age: 7
    stdout: true
  evaluation:
    enabled: true
    path: "/var/log/openflag/evaluation.log"
    max-size: 1024
    max-backups: 7
    max-age: 7

server:
  address: :7677
  read-timeout: 20s
  write-timeout: 20s
  graceful-timeout: 5s

database:
  driver: postgres
  master-conn-string: postgresql://openflag:secret@127.0.0.1:5432/openflag?sslmode=disable&connect_timeout=30
  slave-conn-string: postgresql://openflag:secret@127.0.0.1:5432/openflag?sslmode=disable&connect_timeout=30
  options:
    connection-lifetime: 30m
    max-open-connections: 10
    max-idle-connections: 5

redis:
  master-address: 127.0.0.1:6379
  slave-address: 127.0.0.1:6379
  options:
    sentinel: false
    master-name: mymaster
    password: ""
    pool-size: 0
    min-idle-conns: 20
    dial-timeout: 5s
    read-timeout: 3s
    write-timeout: 3s
    pool-timeout: 4s
    idle-timeout: 5m
    max-retries: 5
    min-retry-backoff: 1s
    max-retry-backoff: 3s

evaluation:
  entity-context-cache-expiration: 1h
  update-flags-cron-pattern: "0 0/5 * * * *"

monitoring:
  prometheus:
    enabled: true
    address: ":9001"
