apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openflag.fullname" . }}
  labels:
    {{- include "openflag.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl (.Files.Get "conf/config.yaml") . | quote }}
