# Default values for openflag.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openflag/openflag
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: "openflag"
fullnameOverride: "openflag"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/endpoint: "/metrics"
  prometheus.io/port: "9001"

service:
  type: ClusterIP
  http:
    port: 7677
  grpc:
    port: 7678

config:
  database:
    driver: postgres
    master:
      connstr: postgresql://openflag:secret@postgresql:5432/openflag?sslmode=disable&connect_timeout=30
    slave:
      connstr: postgresql://openflag:secret@postgresql:5432/openflag?sslmode=disable&connect_timeout=30
  redis:
    master:
      name: mymaster
      address: redis:6379
    slave:
      address: redis:6379
    sentinel: false
    password: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: openflag
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: openflag.com
      paths:
        - /
  tls: []
  #  - secretName: openflag-tls
  #    hosts:
  #      - openflag.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
