logger:
  access:
    enabled: false
    path: "/var/log/openflag/access.log"
    format: "${remote_ip} - - [${time_rfc3339}] \"${method} ${uri} HTTP/1.1\" ${status} \
    ${bytes_out} ${bytes_in} ${latency} \"${referer}\" \"${user_agent}\"\n"
    max-size: 1024
    max-backups: 7
    max-age: 7
  app:
    level: info
    path: "/var/log/openflag/app.log"
    max-size: 1024
    max-backups: 7
    max-age: 7
    stdout: true
  evaluation:
    enabled: false
    path: "/var/log/openflag/evaluation.log"
    max-size: 1024
    max-backups: 7
    max-age: 7

server:
  address: ":{{ .Values.service.http.port }}"
  grpc-address: ":{{ .Values.service.grpc.port }}"
  read-timeout: 20s
  write-timeout: 20s
  graceful-timeout: 5s

database:
  driver: "{{ .Values.config.database.driver }}"
  master-conn-string: "{{ .Values.config.database.masterConnStr }}"
  slave-conn-string: "{{ .Values.config.database.slaveConnStr }}"
  options:
    connection-lifetime: 30m
    max-open-connections: 10
    max-idle-connections: 5

redis:
  master-address: "{{ .Values.config.redis.masterAddress }}"
  slave-address: "{{ .Values.config.redis.slaveAddress }}"
  options:
    sentinel: {{ .Values.config.redis.masterSentinel }}
    master-name: "{{ .Values.config.redis.masterName }}"
    password: "{{ .Values.config.redis.password }}"
    pool-size: 0
    min-idle-conns: 20
    dial-timeout: 5s
    read-timeout: 3s
    write-timeout: 3s
    pool-timeout: 4s
    idle-timeout: 5m
    max-retries: 5
    min-retry-backoff: 1s
    max-retry-backoff: 3s

evaluation:
  entity-context-cache-expiration: 1h
  update-flags-cron-pattern: "0 0/5 * * * *"

monitoring:
  prometheus:
    enabled: true
    address: ":{{ .Values.metrics.port }}"
